### ISSUE TITLE
not displaying

### ISSUE THREAD

**Issue by ChrisRG711** [MMRIZE/MMM-CalendarExt3#100]
Sorry if this is a newbie or obvious question. I have followed the instructions to add. Updated the default calendar as it shows. but the page is blank when it is displayed. Here is my config. The second calendars URL has the full url without the token for obvious reasons.
Can you see anything wrong with the below. 

{
  module: "MMM-CalendarExt3",
  position: "bottom_bar",
  title: "my calendars",
  config: {
      mode: "month",
      instanceId: "calendars",
      locale: 'en-US',
      calendarSet: ['us_holiday','work']
  }
},
{
  module: "calendar",
  position: "middle_center",
  config: {
    broadcastPastEvents: true, // <= IMPORTANT to see past events
    calendars: [
      {
        url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics",
        name: "us_holiday", // <= RECOMMENDED to assign name
        color: "red" // <= RECOMMENDED to assign color
      },
{
	name: "work",
	color: "blue",
	symbol: "calendar-check",
	url: "https://outlook.office365.com/owa/calendar/calendar.ics"
}
]
}
},

**Comment by Pollard-J** [comment]
I have the same problem with mine. I've just updated as it was 1 commit behind, and now the calendar is not displaying any events.

**Comment by ChrisRG711** [comment]
no dice. I can see it in the log getting the info. 

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/9805053/7252c20b-34bc-4cb4-9110-bc1f0459b232)

**Comment by eouia** [comment]
You're looking `Backend-log`, but this module doesn't use `node_helper.js`, so that information is useless. Can you see the frontend-log? (in Developer tools of Browser/Electron Chromium wrapper) => I'll leave the instructions below;.

**General Guide**
1. Remove the module and reinstall again.
https://github.com/MMRIZE/MMM-CalendarExt3#install-or-update

2. Try minimal configuration.
Back up your config, then use the test configuration in the example folder. (rename it to `config.js`, then copy it to the main MM directory)
If it works, the issue would lay on other modules or just your misconfiguration. You can start your trial from it.

3. Activate the front-dev console.
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> will open the front-dev console (Developer Tools) on your MM Screen.
(Or in some environments, it will be the different key combination like `F12` or `Shift + Command + j`)
In the `console` tab, you can see many helpful logs, including suspicious errors also. 
> `[CX3] Module is not prepared yet, wait a while.` is not an error, just a warning. you can ignore it.)
If you find a suspicious error message that you think is related to the cause, Report me with a screen capture or a snap with your Handy.

When you are using a dumb terminal so you cannot open the front-dev console with a keyboard, you can manually execute the MM on dev mode. (You should STOP `PM2` before this.)
```sh
npm run start:dev
```

4. Report exact information to represent.
To represent your issue, I need these pieces of information.
- Your device :  (e.g. RPI 4B 4GB, MBP M1Max)
- OS & Version : (e.g. RPOS Bullseye, MacOS Sonoma)
- Node, NPM version : (e.g. node 16.4.1, npm 8.5.1)
> you can check with `npm -v` and `node -v`
- MM version : (e.g. 2.25.0)
- How you are running MM. (e.g. Dedicated Electron client, Chrome Browser with Serveronly mode)
- Browser(Electron/Chromium) Version. : (e.g. Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36)
> You can check this info by typing `navigator.userAgent` in the last line of the console tab of developer tools.

If you think the issue is related to the specific calendar,  Send me your full config file (you may need to rename it as `config.txt` with real ics URL to eouia0819@gmail.com . I understand that calendars are sensitive personal information. However, to determine the exact cause, I need it.

**Comment by Pollard-J** [comment]
![16974674920881834440672838576881](https://github.com/MMRIZE/MMM-CalendarExt3/assets/122126351/6139214a-caca-47f9-b19b-c11ab4716a04)
This is my error

**Comment by Pollard-J** [comment]
![Uploading 16974675737406032532365848866793.jpg…]()
And this

**Comment by Pollard-J** [comment]
![1697467647173538467231660702638](https://github.com/MMRIZE/MMM-CalendarExt3/assets/122126351/1b5cccba-ca1a-4067-9b06-7114e38ff9bc)
And this

**Comment by eouia** [comment]
That error seems not directly related to this module.
animate.css is introduced and hosted by MM itself. I think your MM is not properly installed or updated, so it might miss that css file.

**Comment by Pollard-J** [comment]
![20231022_171613](https://github.com/MMRIZE/MMM-CalendarExt3/assets/122126351/1cd03828-2d7c-40f2-8b37-5eba7f6dcce6)
I just had a look on the pm2 logs and saw all of this.

**Comment by eouia** [comment]
As you read those error messages, 
There is `Fetch is not defined error` in `modules/defaults/calendar/calendarFetcher.js. 
Not related to my module. Ask the developer of the default calendar module. You may ask the community. (MagicMirror Forum)

(I think your MM is not installed or updated properly.)

**Comment by Pollard-J** [comment]
thank you. i have raised an issue with the Magic Mirror developers. They said i needed to update to the latest version of Node.js but that still hasnt fixed it yet.

cheers.

**Comment by Arhum2** [comment]
hi im having the same issue,
my MM version is 2.25.0
and this is my config
`	{
	  module: "MMM-CalendarExt3",
	  position: "bottom_bar",
	  title: "",
	  config: {
		mode: "month",
		locale: 'en',
		maxEventLines: 5,
		firstDayOfWeek: 1,
		calendarSet: ['Calendar'],
		useMarquee: true,
		displayEndTime: true,
		displayWeatherTemp: true,
		useWeather: true
		
	  }
	},
	{
			module: "calendar",
			header: "Calendar",
			position: "top_right",
			config: {
				calendars: [
					{
						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "LINK",
						color: "orange"
					}
				]
			}
		},

**Comment by eouia** [comment]
What is the same issue? Show me more details like front-end and back-end logs or screenshot to know what happen.

**Comment by Arhum2** [comment]
heres what i see on the mirror
![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/82200170/ae14994c-6a14-4a9b-9f2e-df7ce274da3b)
and here are the logs
`[22.12.2023 02:40.12.559] [LOG]   Refreshed access token because it has expired. Expired at: 02:40:05 now is: 02:40:12
[22.12.2023 02:40.12.574] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.641] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.776] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.787] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.795] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.852] [INFO]  Checking git for module: MMM-PIR-Sensor-Lite
[22.12.2023 02:40.12.918] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.925] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.931] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.12.937] [LOG]   Refreshed access token because it has expired. Expired at: 03:40:12 now is: 02:40:12
[22.12.2023 02:40.13.041] [INFO]  Checking git for module: MMM-CalendarExt3
[22.12.2023 02:40.13.119] [INFO]  Checking git for module: MMM-NowPlayingOnSpotify
[22.12.2023 02:40.13.229] [INFO]  Checking git for module: EXT-GooglePhotos
[22.12.2023 02:40.13.372] [INFO]  Checking git for module: EXT-Pages
[22.12.2023 02:40.13.470] [INFO]  Checking git for module: MagicMirror
[22.12.2023 02:40.14.425] [INFO]  Calendar-Fetcher: Broadcasting 158 events from <CALENDAR LINK 2>
[22.12.2023 02:40.14.453] [LOG]   [GATEWAY] [PM2] You don't use PM2
[22.12.2023 02:40.18.404] [INFO]  Calendar-Fetcher: Broadcasting 12 events from <CALENDAR LINK>
[22.12.2023 02:40.21.923] [LOG]   [GATEWAY] [SYSTEMINFO] Read Uptimed
[22.12.2023 02:40.21.924] [LOG]   [GATEWAY] [SYSTEMINFO] Initialized
`

**Comment by eouia** [comment]
First, ref. [this](https://github.com/MMRIZE/MMM-CalendarExt3/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) (If you post your issue as a new one, you may get the instruction for self-test)

I suggest you try the simplest config in example folder (https://github.com/MMRIZE/MMM-CalendarExt3/blob/main/example/minimal.config.js). After that try to add one-by-one.

**Comment by Pollard-J** [comment]
I raised an issue with Magic Mirror and this was how to fix it.

https://github.com/MichMich/MagicMirror/issues/3245
