### ISSUE TITLE
ReferenceError: Log is not defined

### ISSUE THREAD

**Issue by marcx28** [MMRIZE/MMM-CalendarExt3#103]
Hello, following error message appears after each start of MagicMirror. The module somehow works fine.

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/35005352/9fd42f81-fbb6-44a7-8f75-99c8a866b28f)

**Comment by eouia** [comment]
Weird.
`Log` is a window-level global object injected by MagicMirror Core, not by this module. So, it is not the fault of this module.
<img width="502" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/30bda5a5-06d6-4b92-b0ed-a5a528f5f43e">




Could you let me know where you got this error?

Suspicious points are; 
1) your MM core files might be corrupted, so cannot launch `Log` object. 
2) Your other module might overwrite or remove `Log` object by incident.

Have you been able to try my instructions for the Bug Report template issuing?

**Comment by eouia** [comment]
Now I can guess what happens.
MMM-Remote-Control module tried to read some of the internal values of other modules. But instead of parsing it as text, it loads modules directly in the program! Of course, it would be performed on NodeJS environment, and there is no `window` global object, unlike a real Electron/Chromium/Browser client. So it will throw an error. It is such a tricky way to achieve the purpose, I can't like it.

Anyway, I know how to prevent this issue, but I'm still wondering if I should fix my code due to a problem that wasn't my fault. 
Maybe in the next update, I'll consider to fix it.
