### ISSUE TITLE
Calendar Text Color not showing

### ISSUE THREAD

**Issue by B3DTech** [MMRIZE/MMM-CalendarExt3#193]
RPI 5
OS & Version : PiOS Bookworm
- Node, NPM version : node 22.12.0,  npm 10.9.2)
- MM version : 2.29.0
- Electron
- Browser.  Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36

I have multiple calendars set up in the default calendar module.  Each one has colors defined, and the calendar module is set to coloredText: true

```
                       module: "calendar",
                        header: "Family Calendar",
                        position: "top_left",
                        hiddenOnStartup: "true",
                        config: {
                                broadcastPastEvents: true,
                                fade: "false",
                                dateFormat: "llll",
                                dateEndFormat: "llll",
                                timeFormat: "absolute",
                                showEnd: "true",
                                urgency: 0,
                                getRelative: 0,
                                showLocation: "true",
                                showTimeToday: "true",
                                maxTitleLength: 50,
                                maxLocationTitleLength: 50,
                                showLocation: "true",
                                wrapEvents: "true",
                                wrapLocationEvents: "true",
                                coloredText: "true",
                                refreshInterval: "300000",
                                calendars: [
                                        {
                                                name: "max_soccer",
                                                symbol: "futbol",
                                                color: "#75c553",
                                                url: "https://sportsix.sports-it.com/...........>
                                        },

```

The symbol in MMM-CalendarExt3 shows up with the set color code, but the text is default white.

`<div class="event calendar_volleyball passed singleday" data-calendar-seq="5" data-calendar-name="volleyball" data-color="#af55c0" data-description="Type: Match  Opponent: Hudson  Bus: 4:00PM  Dismissal:   Est.return:   " data-title="Volleyball: Boys Modified (7-8-9)  vs. Hudson (Away)" data-full-day-event="false" data-geo="false" data-location="Hudson High School  " data-start-date="1734386400000" data-end-date="1734386400000" data-today="false" data-symbol="fas fa-fw fa-volleyball" style="--calendarColor: #af55c0; --oppositeColor: white; grid-column: 2 / 3;" id="5_1734386400000_1734386400000_1734890993587" data-popoverble="true"><div class="headline useSymbol"><span class="symbol"><span class="fas fa-fw fa-volleyball"></span></span><div class="time startTime notInDay"><span class="eventTimeParts hour seq_0">5</span><span class="eventTimeParts literal seq_1">:</span><span class="eventTimeParts minute seq_2">00</span><span class="eventTimeParts literal seq_3"> </span><span class="eventTimeParts dayPeriod seq_4">PM</span></div><div class="time endTime notInDay"><span class="eventTimeParts hour seq_0">5</span><span class="eventTimeParts literal seq_1">:</span><span class="eventTimeParts minute seq_2">00</span><span class="eventTimeParts literal seq_3"> </span><span class="eventTimeParts dayPeriod seq_4">PM</span></div><div class="title marquee"><span class="marqueeText" style="--marqueeOffset: 2px; --marqueeScroll: 333px; --marqueeLength: 331s;">Volleyball: Boys Modified (7-8-9)  vs. Hudson (Away)</span></div></div><div class="description">Type: Match  Opponent: Hudson  Bus: 4:00PM  Dismissal:   Est.return:   </div><div class="location">Hudson School  </div></div>`

You can see that it is sending the --calendarColor and data-color, but it's not applying to the text.

<img width="592" alt="image" src="https://github.com/user-attachments/assets/c5241c34-0891-4777-b572-f72138712d8b" />

<img width="115" alt="image" src="https://github.com/user-attachments/assets/28db4a08-752d-478f-9d87-31c7d48a512e" />

**Comment by eouia** [comment]
I just wanted to let you know that that is intended. It's not a bug.
By default, 
- Fullday / Multiday events : colored(`--calendarColor`) background, white/black(`--oppositeColor`) text & symbol
- normal events: transparent background, colored(`--calendarColor`) symbol, white(`--defaultColor`) text

I hate the colorful text, so that is the intended design. 

If you want to have a colored text, you can assign the `--calendarColor` to that specific element's CSS

**Comment by B3DTech** [comment]
The colored text helps immensely when you have 5 exceptionally busy people in the house and need to see who has what when quickly.  It's a bit less obvious when only seeing the color of the symbol since it's pretty small.

I guess for now I'll update my CSS, but every update will overwrite it.  To me it makes sense to make the default your preference since it's your module (thank you for it by the way, it's awesome), but allow the option for people to carry over the feature of the default calendar and select the option to enable colored text in their config.

**Comment by eouia** [comment]
> I guess for now I'll update my CSS, but every update will overwrite it. To me it makes sense to make the default your preference since it's your module (thank you for it by the way, it's awesome), but allow the option for people to carry over the feature of the default calendar and select the option to enable colored text in their config.

I cannot understand this.
Overriding CSS in `custom.css` doesn't make any overwriting/reset on updates. (Did you modify `MMM-CalendarExt3.css` directly?)

```css
/* css/custom.css */
.CX3 .event.singleday .headline .title {
  color: var(--calendarColor);
}
```
<img width="285" alt="image" src="https://github.com/user-attachments/assets/8da29957-c287-4305-b041-849945d0d63c" />

By the way.
That, too, is an intentional design choice. I design my modules so that visual presentation is as much as possible controlled solely by CSS. Unless related to structural or functional aspects, all visible design elements are handled purely by CSS.  

While offering various options to users is undoubtedly desirable, there are a few reasons I avoid this approach:  
- User needs are incredibly diverse, and trying to implement all possible cases makes the module too large and complex.  
- I don't see the need to provide additional options for elements that can already be controlled using CSS.  

(For the same reason, unlike other MM module developers, I frequently use a technique where users can directly customize part of the module's logic by using callback functions in the config instead of offering options. Thanks to this, my modules have excellent extensibility, but they're notoriously tricky to use...)

**Comment by MaxDiOrio** [comment]
Still super new to MM (few days) - didn't realize there was a custom CSS file - moved it there and it works great.
