### ISSUE TITLE
Calendar flashing in 'week' mode.

### ISSUE THREAD

**Issue by sideeyesadie** [MMRIZE/MMM-CalendarExt3#3]
Hello. I cannot seem to figure out if I have something set up incorrectly or if I am missing information in my code, however my calendar flashes in 'week' mode. Even with the most basic code consisting of only:
`
{
  module: "MMM-CalendarExt3",
  position: "bottom_center",
},
`
the calendar flashes on the screen. The flashing is not rhythmic but is about once every half second to second. If I add in mode: "month", in the config line I get the calendar to fill the entire screen and it does not flash and operates as it should. I am running the default MM calendar module as well without issue. I have tried deleting and reinstalling the module as well as checking for an update and everything show up to date. I have also tried various different combinations of code trying to get it to work in week mode but it always flashes. Anything I should be doing different with the CalendarExt3 line of code or the default Calendar line of code?

**Comment by eouia** [comment]
Show me your config.js (specific for this module and your original calendar module)
The expected behaviour of refreshing is done by calendar fetch. When a fetching of a calendar(.ics) is finished, this module will be refreshed, but not by mode. So this is somewhat weird. Let me look inside.

At this moment, I suspect many calendars fetching simultaneously. Usually, the month view takes a bit long time to draw than the week view, so fetching might be stacked on drawing time. But week view is so quick to draw. 

I will consider `minimumRedrawInterval`. After fixing it, I'll notify you.

**Comment by sideeyesadie** [comment]
I did some more debugging and figured it out. The issue was on my end with the default calendar config I had set up. You were right, it was with the fetch interval of the of the default calendar module. The documentation on the MM website for the calendar module says the default fetchInterval should be 300000 (5 minutes). I didn't add this to my line of code because 5 minutes is more than enough for me. However after more digging, the actual default fetchInterval was at 2000. I am running 4 calendars so sounds like it was fetching 4 calendars every 2 seconds which would explain why it was flashing so much. I added `fetchInterval: 300000,` to the default calendar config.js and it is running properly now. Thanks for the insight, I am still learning a lot of this.
