### ISSUE TITLE
Entire module flashes on update

### ISSUE THREAD

**Issue by mikalj2009** [MMRIZE/MMM-CalendarExt3#46]
I use the calendar in a three week view, holding 6 calendars.
When they update, the entire module flashes several times.

Is there a way to change this behaviour, so only the events/text changes?

**Comment by eouia** [comment]
It is caused by your six calendars fetching happens not together or in enough short time.
Your calendars might be fetched one by one with an annoying time gap, for example, calendar A is fetched, then after 10 seconds, calendar B is fetched, and then after 15 seconds calendar C is fetched, ...

To prevent this;
1) Adjust your calendar fetching schedule to be completed together or at least in similar periods.
2) You can adjust `waitFetch`  to ignore too frequent fetch-refreshing. If you set `waitFetch: 60 * 1000`, this module will not refresh the view immediately and will wait 60 seconds to take another fetching followed. If there is no more following fetching in 60 seconds, then the module will redraw the view.
The drawback is the update of events would be not applied at least during this `waitFetch` time. Just give it enough time if you don't mind an immediate update.

**Comment by SlamminS85** [comment]
I am still seeing the calendar constantly refreshing when hosting multiple calendars (4 in my case) and setting waitFetch to be 5 minutes 

It will wait for long periods and then suddenly refresh 6+ times in a row.

**Comment by eouia** [comment]
I'll see.

**Comment by SlamminS85** [comment]
I was able to partially resolve this with these added lines:

      if (this.fetchTimer) {
        clearTimeout(this.fetchTimer)
        this.fetchTimer = null
        if (this.initialLoadCount <= calc(calendarSet.length + 2)){ /* start new code */
                this.config.waitFetch = 1000
                this.initialLoadCount = this.initialLoadCount + 1
        } else {
                this.config.waitFetch = 300000
        } /*end new code*/

      }

**Comment by eouia** [comment]
Check #31

**Comment by SlamminS85** [comment]
I will check this out here this weekend. Thanks!
