### ISSUE TITLE
Calendar shrank?

### ISSUE THREAD

**Issue by arvydasg** [MMRIZE/MMM-CalendarExt3#59]
Hello!

First of all, thank you for this great addon, I have been using it daily for over half a year!

I have noticed that the calendar in the `main` branch appears as such. All shrunk up, not taking the whole given width:

![main_banch](https://user-images.githubusercontent.com/78803192/225831853-9c08038f-b332-4e1a-a10b-d6b7e5b70a01.png)

When in any of the `dev` branches, as such(ignore the fact that there are no events - the screenshot was taken before the reload):

![dev_branch](https://user-images.githubusercontent.com/78803192/225831911-c80ea9e0-3334-4ee8-a4b6-4157ed69c582.png)

I was just changing the branches, not my config files.

I much prefer the result of the `dev` branch.

My config for MMM-CalendarExt3 looks like this:

```
{
	    module: "MMM-CalendarExt3",
	    position: "bottom_center",
	    title: "",
	    config: {
		mode: "week",
		instanceId: "basicCalendar",
		maxEventLines: 5,
		fontSize: '22px',
		eventHeight: '23px',
		// firstDayOfWeek: 1,
		maximumNumberOfDays: 365,
		// maximumEntries: 200,
		// weekIndex: 1,
		calendarSet: ['xxxx', 'xxxx'],
	    }
	},
```

**Comment by eouia** [comment]
If you want to use full-width of area, Don't use `center`. **You can use `bottom_bar` instead of `bottom_center`.**
`center` area of MM layout has some bug(? or side-effect) because, center area has not fixed/pre-calculated width, it will change it's size after rendering with CSS transformatting, but at that time, it lose its unit.
